## Se importan las librerías

In [1]:
import numpy as np
import pandas as pd

## Se cargan los dataframes

In [2]:
data_2020 = pd.read_csv(r'C:\Users\nadpe\OneDrive\Documentos\Tec. Datos\Aprendizaje automático\linea144\Data\external\linea144-2020.csv')
data_2020.head(10)

,fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,tipo_de_violencia_domestica,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora
0,2020-01-01,Tucumán,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon
1,2020-01-01,Buenos Aires,Mujer,39.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
2,2020-01-01,Buenos Aires,Mujer,22.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
3,2020-01-01,Buenos Aires,Mujer,53.0,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon
4,2020-01-01,Buenos Aires,Mujer,38.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon
5,2020-01-01,Buenos Aires,Mujer,23.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon
6,2020-01-01,Santiago Del Estero,Mujer,25.0,Paraguaya,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon
7,2020-01-01,Santa Fe,Mujer,24.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
8,2020-01-01,Santa Fe,Mujer,NaN,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon
9,2020-01-01,San Juan,Mujer,21.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon

In [3]:
data_2020.shape

(29706, 19)

In [4]:
data_2021 = pd.read_csv(r'C:\Users\nadpe\OneDrive\Documentos\Tec. Datos\Aprendizaje automático\linea144\Data\external\linea144-2021.csv')
data_2021.head(10)

,fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,tipo_de_violencia_domestica,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora
0,2021-01-01,Buenos Aires,Mujer,73.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon
1,2021-01-01,Buenos Aires,Mujer,32.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
2,2021-01-01,Ciudad Autónoma de Buenos Aires,Mujer,33.0,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
3,2021-01-01,Ciudad Autónoma de Buenos Aires,Mujer,45.0,Argentina,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
4,2021-01-01,Ciudad Autónoma de Buenos Aires,Mujer,32.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
5,2021-01-01,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
6,2021-01-01,Buenos Aires,Mujer,53.0,Argentina,Si,Si,Si,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
7,2021-01-01,La Rioja,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,NaN
8,2021-01-01,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,NaN
9,2021-01-01,Santa Fe,Mujer,28.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon

In [5]:
data_2021.shape

(25301, 19)

In [6]:
data_2022 = pd.read_csv(r'C:\Users\nadpe\OneDrive\Documentos\Tec. Datos\Aprendizaje automático\linea144\Data\external\linea144-enero-diciembre-2022.csv')
data_2022.head(10)

,Fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,tipo_de_violencia_domestica,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora,Unnamed: 19
0,2022-01-01,Buenos Aires,Mujer,31.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,NaN
1,2022-01-01,Buenos Aires,Mujer,31.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Otro familiar,Varon,NaN
2,2022-01-01,Ciudad Autónoma de Buenos Aires,Mujer,29.0,Boliviana,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon,NaN
3,2022-01-01,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,NaN
4,2022-01-01,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,NaN
5,2022-01-01,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,NaN
6,2022-01-01,Buenos Aires,Mujer,43.0,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon,NaN
7,2022-01-01,Buenos Aires,Mujer,30.0,Paraguaya,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,NaN
8,2022-01-01,Santiago Del Estero,Mujer,27.0,Argentina,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,NaN
9,2022-01-01,Santa Fe,Mujer,NaN,NaN,Si,Si,Si,No,No,No,No,No,No,No,No,No,Otro,Varon,NaN

In [7]:
data_2022.shape

(24558, 20)

In [8]:
data_2023 = pd.read_csv(r'C:\Users\nadpe\OneDrive\Documentos\Tec. Datos\Aprendizaje automático\linea144\Data\external\linea144-enero-junio-2023.csv')
data_2023.head(10)

,Fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,tipo_de_violencia_domestica,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora
0,2023-01-01,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon
1,2023-01-01,Buenos Aires,Mujer,19.0,Argentina,Si,Si,Si,No,No,No,No,No,No,No,No,No,Otro,Varon
2,2023-01-01,Buenos Aires,Mujer,46.0,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon
3,2023-01-01,Entre Ríos,Mujer,28.0,NaN,No,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon
4,2023-01-01,Mendoza,Mujer,34.0,Argentina,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon
5,2023-01-01,Buenos Aires,Mujer,38.0,Paraguaya,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon
6,2023-01-01,Buenos Aires,Mujer,57.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon
7,2023-01-01,Tucumán,Mujer,NaN,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon
8,2023-01-01,Santa Fe,Mujer,39.0,Argentina,Si,Si,Si,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon
9,2023-01-01,Mendoza,Mujer,24.0,Argentina,Si,Si,Si,Si,No,Si,No,No,No,No,No,No,Pareja,Varon

In [9]:
data_2023.shape

(9976, 19)

## Se unen los dataframes

In [10]:
data_total = pd.concat([data_2020, data_2021, data_2022, data_2023])
data_total.head(10)

,fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,...,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora,Fecha,Unnamed: 19
0,2020-01-01,Tucumán,Mujer,NaN,NaN,Si,Si,No,No,No,...,No,No,No,No,No,No,Pareja,Varon,NaN,NaN
1,2020-01-01,Buenos Aires,Mujer,39.0,NaN,Si,Si,No,No,No,...,No,No,No,No,No,No,Ex pareja,Varon,NaN,NaN
2,2020-01-01,Buenos Aires,Mujer,22.0,Argentina,Si,Si,No,No,No,...,No,No,No,No,No,No,Ex pareja,Varon,NaN,NaN
3,2020-01-01,Buenos Aires,Mujer,53.0,NaN,No,Si,No,No,No,...,No,No,No,No,No,No,Pareja,Varon,NaN,NaN
4,2020-01-01,Buenos Aires,Mujer,38.0,Argentina,Si,Si,No,No,No,...,No,No,No,No,No,No,Pareja,Varon,NaN,NaN
5,2020-01-01,Buenos Aires,Mujer,23.0,Argentina,Si,Si,No,Si,No,...,No,No,No,No,No,No,Ex pareja,Varon,NaN,NaN
6,2020-01-01,Santiago Del Estero,Mujer,25.0,Paraguaya,Si,Si,No,Si,No,...,No,No,No,No,No,No,Pareja,Varon,NaN,NaN
7,2020-01-01,Santa Fe,Mujer,24.0,Argentina,Si,Si,No,No,No,...,No,No,No,No,No,No,Ex pareja,Varon,NaN,NaN
8,2020-01-01,Santa Fe,Mujer,NaN,Argentina,Si,Si,No,Si,No,...,No,No,No,No,No,No,Pareja,Varon,NaN,NaN
9,2020-01-01,San Juan,Mujer,21.0,Argentina,Si,Si,No,Si,No,...,No,No,No,No,No,No,Pareja,Varon,NaN,NaN

In [11]:
data_total.shape
data_total.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89541 entries, 0 to 9975
Data columns (total 21 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   fecha                                              55007 non-null  object
 1   prov_residencia_persona_en_situacion_violencia     88377 non-null  object
 2   genero_persona_en_situacion_de_violencia           87637 non-null  object
 3   edad_persona_en_situacion_de_violencia             72263 non-null  float64
 4   pais_nacimiento_persona_en_situacion_de_violencia  59260 non-null  object
 5   tipo_de_violencia_fisica                           89541 non-null  object
 6   tipo_de_violencia_psicologica                      89541 non-null  object
 7   tipo_de_violencia_sexual                           89541 non-null  object
 8   tipo_de_violencia_economica_y_patrimonial          89541 non-null  object
 9   tipo_de_violencia_simbolica                        89541 non-null  object
 10  tipo_de_violencia_domestica                        89541 non-null  object
 11  modalidad_de_violencia_institucional               89541 non-null  object
 12  modalidad_de_violencia_laboral                     89541 non-null  object
 13  modalidad_violencia_contra_libertad_reproductiva   89541 non-null  object
 14  modalidad_de_violencia_obstetrica                  89541 non-null  object
 15  modalidad_de_violencia_mediatica                   89541 non-null  object
 16  modalidad_de_violencia_otras                       89541 non-null  object
 17  vinculo_con_la_persona_agresora                    86146 non-null  object
 18  genero_de_la_persona_agresora                      80328 non-null  object
 19  Fecha                                              34534 non-null  object
 20  Unnamed: 19                                        0 non-null      float64
dtypes: float64(2), object(19)
memory usage: 15.0+ MB

## Se limpia el data frame

In [12]:
data_total = data_total.drop(["Unnamed: 19"], axis = 1)
#Se elimina una columna que estaba vacía

In [13]:
data_total.info()
#Se observa que en la unión se han duplicado las columnas de fecha por tener distinto nombre.

<class 'pandas.core.frame.DataFrame'>
Index: 89541 entries, 0 to 9975
Data columns (total 20 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   fecha                                              55007 non-null  object
 1   prov_residencia_persona_en_situacion_violencia     88377 non-null  object
 2   genero_persona_en_situacion_de_violencia           87637 non-null  object
 3   edad_persona_en_situacion_de_violencia             72263 non-null  float64
 4   pais_nacimiento_persona_en_situacion_de_violencia  59260 non-null  object
 5   tipo_de_violencia_fisica                           89541 non-null  object
 6   tipo_de_violencia_psicologica                      89541 non-null  object
 7   tipo_de_violencia_sexual                           89541 non-null  object
 8   tipo_de_violencia_economica_y_patrimonial          89541 non-null  object
 9   tipo_de_violencia_simbolica                        89541 non-null  object
 10  tipo_de_violencia_domestica                        89541 non-null  object
 11  modalidad_de_violencia_institucional               89541 non-null  object
 12  modalidad_de_violencia_laboral                     89541 non-null  object
 13  modalidad_violencia_contra_libertad_reproductiva   89541 non-null  object
 14  modalidad_de_violencia_obstetrica                  89541 non-null  object
 15  modalidad_de_violencia_mediatica                   89541 non-null  object
 16  modalidad_de_violencia_otras                       89541 non-null  object
 17  vinculo_con_la_persona_agresora                    86146 non-null  object
 18  genero_de_la_persona_agresora                      80328 non-null  object
 19  Fecha                                              34534 non-null  object
dtypes: float64(1), object(19)
memory usage: 14.3+ MB

In [16]:
data_total.tail(40)
#Se comprueba la duplicación de columnas de fecha. Corresponden a las últimas cargadas.

,fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,tipo_de_violencia_domestica,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora,Fecha
9936,NaN,Catamarca,Mujer,25.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9937,NaN,Chaco,Mujer,34.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,NaN,2023-06-30
9938,NaN,Salta,Mujer,46.0,Argentina,Si,Si,Si,Si,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9939,NaN,Entre Ríos,Mujer,37.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,NaN,2023-06-30
9940,NaN,Córdoba,Mujer,NaN,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9941,NaN,Córdoba,Mujer,36.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,NaN,2023-06-30
9942,NaN,Santa Fe,Mujer,38.0,Argentina,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9943,NaN,Buenos Aires,Mujer,45.0,NaN,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9944,NaN,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9945,NaN,Buenos Aires,Mujer,31.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9946,NaN,Buenos Aires,Mujer,28.0,NaN,Si,Si,Si,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9947,NaN,San Juan,Mujer,42.0,NaN,Si,No,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9948,NaN,Buenos Aires,Mujer,27.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9949,NaN,Neuquén,Mujer,30.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9950,NaN,Buenos Aires,Mujer,24.0,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9951,NaN,Buenos Aires,Mujer,27.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9952,NaN,Buenos Aires,Mujer,42.0,Argentina,Si,Si,Si,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9953,NaN,Buenos Aires,Mujer,63.0,Argentina,No,Si,No,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9954,NaN,Buenos Aires,Mujer,63.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9955,NaN,Buenos Aires,Mujer,27.0,Argentina,No,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9956,NaN,Buenos Aires,Mujer,36.0,NaN,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9957,NaN,Buenos Aires,Mujer,29.0,Argentina,No,Si,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9958,NaN,Buenos Aires,Mujer,49.0,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9959,NaN,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,Si,No,No,No,No,No,No,No,Otro,Mujer,2023-06-30
9960,NaN,Ciudad Autónoma de Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,NaN,Varon,2023-06-30
9961,NaN,Ciudad Autónoma de Buenos Aires,Mujer,58.0,Argentina,No,No,Si,No,No,Si,No,No,No,No,No,Si,Ex pareja,Varon,2023-06-30
9962,NaN,Ciudad Autónoma de Buenos Aires,NaN,NaN,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9963,NaN,Ciudad Autónoma de Buenos Aires,Mujer,47.0,Argentina,No,Si,No,Si,No,No,No,No,No,No,No,Si,Otro,NaN,2023-06-30
9964,NaN,Ciudad Autónoma de Buenos Aires,Mujer,23.0,Boliviana,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9965,NaN,Ciudad Autónoma de Buenos Aires,Mujer,NaN,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9966,NaN,Ciudad Autónoma de Buenos Aires,NaN,NaN,NaN,Si,Si,Si,Si,No,Si,No,No,No,No,No,No,NaN,NaN,2023-06-30
9967,NaN,Ciudad Autónoma de Buenos Aires,NaN,39.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9968,NaN,Ciudad Autónoma de Buenos Aires,Mujer,44.0,Argentina,No,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9969,NaN,Buenos Aires,NaN,NaN,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,NaN,NaN,2023-06-30
9970,NaN,Ciudad Autónoma de Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9971,NaN,Ciudad Autónoma de Buenos Aires,Mujer,53.0,NaN,No,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9972,NaN,Sin datos,Mujer,19.0,Argentina,No,Si,Si,No,No,Si,No,No,No,No,No,No,Padre o tutor,Varon,2023-06-30
9973,NaN,Ciudad Autónoma de Buenos Aires,Mujer,18.0,Argentina,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9974,NaN,Ciudad Autónoma de Buenos Aires,Mujer,27.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9975,NaN,Ciudad Autónoma de Buenos Aires,Mujer,20.0,NaN,No,Si,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,NaN,2023-06-30

In [17]:
data_total['fecha'].fillna(data_total['Fecha'], inplace=True)
data_total.tail(40)

,fecha,prov_residencia_persona_en_situacion_violencia,genero_persona_en_situacion_de_violencia,edad_persona_en_situacion_de_violencia,pais_nacimiento_persona_en_situacion_de_violencia,tipo_de_violencia_fisica,tipo_de_violencia_psicologica,tipo_de_violencia_sexual,tipo_de_violencia_economica_y_patrimonial,tipo_de_violencia_simbolica,tipo_de_violencia_domestica,modalidad_de_violencia_institucional,modalidad_de_violencia_laboral,modalidad_violencia_contra_libertad_reproductiva,modalidad_de_violencia_obstetrica,modalidad_de_violencia_mediatica,modalidad_de_violencia_otras,vinculo_con_la_persona_agresora,genero_de_la_persona_agresora,Fecha
9936,2023-06-30,Catamarca,Mujer,25.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9937,2023-06-30,Chaco,Mujer,34.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,NaN,2023-06-30
9938,2023-06-30,Salta,Mujer,46.0,Argentina,Si,Si,Si,Si,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9939,2023-06-30,Entre Ríos,Mujer,37.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,NaN,2023-06-30
9940,2023-06-30,Córdoba,Mujer,NaN,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9941,2023-06-30,Córdoba,Mujer,36.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,NaN,2023-06-30
9942,2023-06-30,Santa Fe,Mujer,38.0,Argentina,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9943,2023-06-30,Buenos Aires,Mujer,45.0,NaN,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9944,2023-06-30,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9945,2023-06-30,Buenos Aires,Mujer,31.0,Argentina,Si,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9946,2023-06-30,Buenos Aires,Mujer,28.0,NaN,Si,Si,Si,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9947,2023-06-30,San Juan,Mujer,42.0,NaN,Si,No,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9948,2023-06-30,Buenos Aires,Mujer,27.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9949,2023-06-30,Neuquén,Mujer,30.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9950,2023-06-30,Buenos Aires,Mujer,24.0,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9951,2023-06-30,Buenos Aires,Mujer,27.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9952,2023-06-30,Buenos Aires,Mujer,42.0,Argentina,Si,Si,Si,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9953,2023-06-30,Buenos Aires,Mujer,63.0,Argentina,No,Si,No,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9954,2023-06-30,Buenos Aires,Mujer,63.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9955,2023-06-30,Buenos Aires,Mujer,27.0,Argentina,No,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9956,2023-06-30,Buenos Aires,Mujer,36.0,NaN,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9957,2023-06-30,Buenos Aires,Mujer,29.0,Argentina,No,Si,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9958,2023-06-30,Buenos Aires,Mujer,49.0,Argentina,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9959,2023-06-30,Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,Si,No,No,No,No,No,No,No,Otro,Mujer,2023-06-30
9960,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,NaN,Varon,2023-06-30
9961,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,58.0,Argentina,No,No,Si,No,No,Si,No,No,No,No,No,Si,Ex pareja,Varon,2023-06-30
9962,2023-06-30,Ciudad Autónoma de Buenos Aires,NaN,NaN,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9963,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,47.0,Argentina,No,Si,No,Si,No,No,No,No,No,No,No,Si,Otro,NaN,2023-06-30
9964,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,23.0,Boliviana,Si,Si,No,No,Si,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9965,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,NaN,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9966,2023-06-30,Ciudad Autónoma de Buenos Aires,NaN,NaN,NaN,Si,Si,Si,Si,No,Si,No,No,No,No,No,No,NaN,NaN,2023-06-30
9967,2023-06-30,Ciudad Autónoma de Buenos Aires,NaN,39.0,Argentina,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9968,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,44.0,Argentina,No,Si,No,Si,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9969,2023-06-30,Buenos Aires,NaN,NaN,NaN,No,Si,No,No,No,Si,No,No,No,No,No,No,NaN,NaN,2023-06-30
9970,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,NaN,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9971,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,53.0,NaN,No,Si,No,Si,No,Si,No,No,No,No,No,No,Pareja,Varon,2023-06-30
9972,2023-06-30,Sin datos,Mujer,19.0,Argentina,No,Si,Si,No,No,Si,No,No,No,No,No,No,Padre o tutor,Varon,2023-06-30
9973,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,18.0,Argentina,Si,Si,No,Si,Si,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9974,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,27.0,NaN,Si,Si,No,No,No,Si,No,No,No,No,No,No,Ex pareja,Varon,2023-06-30
9975,2023-06-30,Ciudad Autónoma de Buenos Aires,Mujer,20.0,NaN,No,Si,No,No,Si,Si,No,No,No,No,No,No,Ex pareja,NaN,2023-06-30

In [19]:
data_total = data_total.drop(["Fecha"], axis = 1) 
data_total.info()
#Se elimina la columna Fecha y se chequea que estén la totalidad de los datos dispuestos en la varible fecha

<class 'pandas.core.frame.DataFrame'>
Index: 89541 entries, 0 to 9975
Data columns (total 19 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   fecha                                              89541 non-null  object
 1   prov_residencia_persona_en_situacion_violencia     88377 non-null  object
 2   genero_persona_en_situacion_de_violencia           87637 non-null  object
 3   edad_persona_en_situacion_de_violencia             72263 non-null  float64
 4   pais_nacimiento_persona_en_situacion_de_violencia  59260 non-null  object
 5   tipo_de_violencia_fisica                           89541 non-null  object
 6   tipo_de_violencia_psicologica                      89541 non-null  object
 7   tipo_de_violencia_sexual                           89541 non-null  object
 8   tipo_de_violencia_economica_y_patrimonial          89541 non-null  object
 9   tipo_de_violencia_simbolica                        89541 non-null  object
 10  tipo_de_violencia_domestica                        89541 non-null  object
 11  modalidad_de_violencia_institucional               89541 non-null  object
 12  modalidad_de_violencia_laboral                     89541 non-null  object
 13  modalidad_violencia_contra_libertad_reproductiva   89541 non-null  object
 14  modalidad_de_violencia_obstetrica                  89541 non-null  object
 15  modalidad_de_violencia_mediatica                   89541 non-null  object
 16  modalidad_de_violencia_otras                       89541 non-null  object
 17  vinculo_con_la_persona_agresora                    86146 non-null  object
 18  genero_de_la_persona_agresora                      80328 non-null  object
dtypes: float64(1), object(18)
memory usage: 13.7+ MB

In [20]:
data_total.to_csv('df_completo.csv')