In [1]:
# carga tabla desde la url https://estudiodelamo.com/cotizacion-historica-dolar-peso-argentina/
import pandas as pd

url = 'https://estudiodelamo.com/cotizacion-historica-dolar-peso-argentina/'
df = pd.read_html(url)

# La función read_html devuelve una lista de DataFrames encontrados en la página.
# Es posible que la tabla que buscas no sea la primera.
# Puedes inspeccionar la lista 'df' para encontrar la tabla correcta.
# Por ejemplo, para mostrar la primera tabla:
if df:
  print(df[0])
else:
  print("No se encontraron tablas en la URL.")

    Unnamed: 0 Variación anual dólar oficial (según último mes del año)  \
0         2011                                              8,06%
1         2012                                             13,99%
2         2013                                             32,62%
3         2014                                             30,45%
4         2015                                             52,48%
5         2016                                             21,71%
6         2017                                             17,20%
7         2018                                            100,00%
8         2019                                             57,61%
9         2020                                             43,53%
10        2021                                             22,22%
11        2022                                             72,24%
12        2023                                            349,79%
13        2024                                             28,45%
14        2025                                             31,01%

          ENE        FEB        MAR        ABR        MAY      JUN      JUL  \
0       $3,99      $4,02      $4,04      $4,07      $4,09    $4,10    $4,14
1       $4,32      $4,34      $4,36      $4,40      $4,46    $4,51    $4,57
2       $4,96      $5,02      $5,10      $5,16      $5,26    $5,36    $5,48
3       $7,87      $7,80      $7,93      $7,93      $8,01    $8,06    $8,12
4       $8,55      $8,63      $8,72      $8,81      $8,90    $8,99    $9,10
5      $13,58     $15,50     $14,40     $14,10     $13,80   $14,80   $14,80
6      $15,70     $15,30     $15,20     $15,20     $15,90   $16,40   $17,45
7      $19,40     $19,85     $19,90     $20,30     $24,40   $28,40   $26,90
8      $36,40     $38,30     $42,30     $43,20     $43,80   $41,50   $42,90
9      $58,00     $59,00     $60,75     $63,75     $65,50   $68,50   $71,25
10     $86,25     $88,75     $91,50     $92,50     $93,75   $94,75   $95,75
11    $104,25    $106,50    $110,00    $114,25    $119,25  $124,00  $129,25
12    $186,00    $196,00    $207,50    $221,00    $237,00  $255,00  $273,50
13    $805,50    $821,00    $836,00    $856,00    $874,00  $890,50  $911,50
14  $1.033,50  $1.044,25  $1.053,50  $1.140,00  $1.145,00      NaN      NaN

        AGO      SEP      OCT      NOV        DIC
0     $4,21    $4,20    $4,24    $4,27      $4,29
1     $4,62    $4,68    $4,75    $4,82      $4,89
2     $5,64    $5,77    $5,90    $6,10      $6,49
3     $8,30    $8,31    $8,40    $8,43      $8,46
4     $9,20    $9,33    $9,46    $9,60     $12,90
5    $14,70   $15,10   $15,00   $15,70     $15,70
6    $17,10   $17,10   $17,45   $17,10     $18,40
7    $36,20   $40,30   $35,00   $36,80     $36,80
8    $57,00   $55,50   $58,22   $57,75     $58,00
9    $73,00   $75,00   $77,50   $80,50     $83,25
10   $96,75   $98,00   $99,00  $100,00    $101,75
11  $137,00  $145,25  $154,50  $166,25    $175,25
12  $347,50  $347,50  $347,50  $358,00    $788,25
13  $932,00  $950,00  $971,50  $991,00  $1.012,50
14      NaN      NaN      NaN      NaN        NaN

In [2]:
# pasar a excel
if df:
  df[0].to_excel('cotizacion_dolar.xlsx', index=False)
  print("La tabla se ha guardado como 'cotizacion_dolar.xlsx'")
else:
  print("No hay tabla para guardar.")

La tabla se ha guardado como 'cotizacion_dolar.xlsx'

In [20]:
# muestra dataframe df solo las 6 filas
df[0].head(5)

,Unnamed: 0,Variación anual dólar oficial (según último mes del año),ENE,FEB,MAR,ABR,MAY,JUN,JUL,AGO,SEP,OCT,NOV,DIC
0,2011,"8,06%","$3,99","$4,02","$4,04","$4,07","$4,09","$4,10","$4,14","$4,21","$4,20","$4,24","$4,27","$4,29"
1,2012,"13,99%","$4,32","$4,34","$4,36","$4,40","$4,46","$4,51","$4,57","$4,62","$4,68","$4,75","$4,82","$4,89"
2,2013,"32,62%","$4,96","$5,02","$5,10","$5,16","$5,26","$5,36","$5,48","$5,64","$5,77","$5,90","$6,10","$6,49"
3,2014,"30,45%","$7,87","$7,80","$7,93","$7,93","$8,01","$8,06","$8,12","$8,30","$8,31","$8,40","$8,43","$8,46"
4,2015,"52,48%","$8,55","$8,63","$8,72","$8,81","$8,90","$8,99","$9,10","$9,20","$9,33","$9,46","$9,60","$12,90"

In [28]:
# crear nuevo dataframe eliminar columna Variación anual dólar oficial
df2 = df[0].drop(columns=['Variación anual dólar oficial (según último mes del año)'])
df2.head(5)

,Unnamed: 0,ENE,FEB,MAR,ABR,MAY,JUN,JUL,AGO,SEP,OCT,NOV,DIC
0,2011,"$3,99","$4,02","$4,04","$4,07","$4,09","$4,10","$4,14","$4,21","$4,20","$4,24","$4,27","$4,29"
1,2012,"$4,32","$4,34","$4,36","$4,40","$4,46","$4,51","$4,57","$4,62","$4,68","$4,75","$4,82","$4,89"
2,2013,"$4,96","$5,02","$5,10","$5,16","$5,26","$5,36","$5,48","$5,64","$5,77","$5,90","$6,10","$6,49"
3,2014,"$7,87","$7,80","$7,93","$7,93","$8,01","$8,06","$8,12","$8,30","$8,31","$8,40","$8,43","$8,46"
4,2015,"$8,55","$8,63","$8,72","$8,81","$8,90","$8,99","$9,10","$9,20","$9,33","$9,46","$9,60","$12,90"

In [29]:
# eliminar las 2 primeras filas
df2 = df2.iloc[2:]
df2.head()

,Unnamed: 0,ENE,FEB,MAR,ABR,MAY,JUN,JUL,AGO,SEP,OCT,NOV,DIC
2,2013,"$4,96","$5,02","$5,10","$5,16","$5,26","$5,36","$5,48","$5,64","$5,77","$5,90","$6,10","$6,49"
3,2014,"$7,87","$7,80","$7,93","$7,93","$8,01","$8,06","$8,12","$8,30","$8,31","$8,40","$8,43","$8,46"
4,2015,"$8,55","$8,63","$8,72","$8,81","$8,90","$8,99","$9,10","$9,20","$9,33","$9,46","$9,60","$12,90"
5,2016,"$13,58","$15,50","$14,40","$14,10","$13,80","$14,80","$14,80","$14,70","$15,10","$15,00","$15,70","$15,70"
6,2017,"$15,70","$15,30","$15,20","$15,20","$15,90","$16,40","$17,45","$17,10","$17,10","$17,45","$17,10","$18,40"

In [33]:
print("Columnas de df2:", df2.columns)
# cambiar nombre de columna "Unnamed: 0" a "Año
df2 = df2.rename(columns={'Unnamed: 0': 'Año'})
print("Columnas de df2 después del cambio:", df2.columns)

Columnas de df2: Index(['Unnamed: 0', 'ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO',
       'SEP', 'OCT', 'NOV', 'DIC'],
      dtype='object')
Columnas de df2 después del cambio: Index(['Año', 'ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO', 'SEP',
       'OCT', 'NOV', 'DIC'],
      dtype='object')
Columnas de df2: Index(['Año', 'ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO', 'SEP',
       'OCT', 'NOV', 'DIC'],
      dtype='object')

In [40]:
# pasar las columnas a filas
# 2. Aplicar pd.melt() para transformar el DataFrame
# id_vars: 'Año' es la columna que queremos mantener fija como identificador.
# var_name: El nombre que queremos darle a la nueva columna que contendrá los nombres de los meses.
# value_name: El nombre que queremos darle a la nueva columna que contendrá los valores.
df_transformado = pd.melt(df2,
                          id_vars=['Año'],
                          var_name='Mes',
                          value_name='Cotizacion') # Usé 'Cotizacion' basado en tu segunda imagen

# 3. Ordenar el DataFrame para que los meses estén en el orden correcto
# Primero, creamos una lista del orden deseado de los meses.
orden_meses = ['ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO', 'SEP', 'OCT', 'NOV', 'DIC']

# Convertimos la columna 'Mes' a un tipo de dato categórico con el orden especificado.
df_transformado['Mes'] = pd.Categorical(df_transformado['Mes'], categories=orden_meses, ordered=True)

# Ordenamos el DataFrame por 'Año' y luego por 'Mes'.
df_final = df_transformado.sort_values(by=['Año', 'Mes']).reset_index(drop=True)
# eliminar filas con vlaores nulos
df_final = df_final.dropna()

print("DataFrame Transformado (como la segunda imagen, o muy similar):")
print(df_final)

DataFrame Transformado (como la segunda imagen, o muy similar):
      Año  Mes Cotizacion
0    2013  ENE      $4,96
1    2013  FEB      $5,02
2    2013  MAR      $5,10
3    2013  ABR      $5,16
4    2013  MAY      $5,26
..    ...  ...        ...
144  2025  ENE  $1.033,50
145  2025  FEB  $1.044,25
146  2025  MAR  $1.053,50
147  2025  ABR  $1.140,00
148  2025  MAY  $1.145,00

[149 rows x 3 columns]

In [41]:
# pasar a excel
# Usamos .empty para verificar si el DataFrame no está vacío antes de intentar guardarlo.
if not df_final.empty:
  df_final.to_excel('cotizacion_dolar-Preprocesado.xlsx', index=False)
  print("La tabla se ha guardado como 'cotizacion_dolar-Preprocesado.xlsx'")
else:
  print("No hay tabla para guardar.")

La tabla se ha guardado como 'cotizacion_dolar-Preprocesado.xlsx'